name: Test Postman Collection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Atualizado para v3
        with:
          node-version: '20'  # Opcional: configura para rodar com Node.js 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run "API PUBLIC - Login e Register - WEB API.postman_collection.json"

